### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by ak3n** [JonPRL/sml-red-jonprl#29]
What about setting fixed-heap size or other options (http://mlton.org/RunTimeOptions)? Because right now mlton takes a lot of memory.

![image](https://cloud.githubusercontent.com/assets/588373/12868427/a531e130-cd17-11e5-8167-4959ce5b0794.png)

And if yes, which size?

**Comment by jonsterling** [comment]
@ak3n Yes, MLton is a bit of a memory hog, but I haven't fiddled with the options... I have a fair amount of memory on my laptop, so I haven't really had any trouble, but you may want to make an adjustment in your own settings.

@MatthewFluet Do you have any advice?

**Comment by jonsterling** [comment]
@ak3n Another option is to use SML/NJ for your personal/development build... I use SML/NJ whenever I'm developing JonPRL, because I can get near instant feedback from the tests, for instance.

**Comment by MatthewFluet** [comment]
The default behavior of MLton is to grow/shrink the heap so that it is approximately 8x live data, with a soft maximum heap of 0.5x physical RAM.

I built 131a516 (omitting the `fixed-heap 0.5g` runtime option) and couldn't replicate the behavior that @ak3n demonstrated.  I see
```
[matthew@shadow sml-red-jonprl]$ mlton @MLton gc-summary -- -mlb-path-map mlb-path-map -output bin/jonprl src/frontend.mlb
GC type         time ms  number           bytes       bytes/sec
-------------   ------- ------- --------------- ---------------
copying           3,002      23   2,136,518,272     711,698,291 
mark-compact          0       0               0               - 
minor                 0       8           3,912               - 
total time: 19,386 ms
total GC time: 3,468 ms (17.9%)
max pause time: 781 ms
total bytes allocated: 16,872,560,392 bytes
max bytes live: 370,468,184 bytes
max heap size: 2,963,808,256 bytes
max stack size: 19,857,408 bytes
num cards marked: 24
bytes scanned: 125,312 bytes
bytes hash consed: 0 bytes
```
which seems pretty typical.  And I do see memory usage top out at about 2G in `top`.

Note the `max bytes live: 370,468,184 bytes`, so the `fixed-heap 0.5g` might not be sufficient as the code continues to grow.

**Comment by ak3n** [comment]
@MatthewFluet My results are similar. 

```
➜  sml-red-jonprl git:(131a516) ✗ mlton @MLton gc-summary -- -mlb-path-map mlb-path-map -output bin/jonprl src/frontend.mlb
Warning: lib/sml-typed-abts/lib/sml-parcom-wrapper/parcom/src/parse.sml 100.58.
  Function is not exhaustive.
    missing pattern: (Unexpected _ | Expected _)
    in: fn Message m => m
Warning: lib/sml-typed-abts/src/patterns/linear_unification.fun 48.11.
  Declaration is not exhaustive.
    missing pattern: ((` _ | $# _), _)
    in: (theta $ es, tau) = Abt.infer m
GC type		time ms	 number		  bytes	      bytes/sec
-------------	-------	-------	---------------	---------------
copying		  4,474	     26	  2,559,651,840	    572,117,085	
mark-compact	      0	      0	              0	              -	
minor		      0	      8	          3,320	              -	
total time: 26,973 ms
total GC time: 4,963 ms (18.4%)
max pause time: 1,173 ms
total bytes allocated: 16,842,219,344 bytes
max bytes live: 374,946,792 bytes
max heap size: 2,034,774,016 bytes
max stack size: 13,926,400 bytes
num cards marked: 24
bytes scanned: 119,168 bytes
bytes hash consed: 0 bytes
```

Sorry, my usual amount of memory (thanks chromium) is 3.5Gb, that's why I have such problem. I think that we can just update `fixed-heap` over progress then.

@jonsterling can you create a build script for SML/NJ or write how do you use it?

**Comment by jonsterling** [comment]
@ak3n What I usually do while developing is load up the SML/NJ repl and run the test suite repeatedly.

First of all, get it fired up:

```
rlwrap sml
> val {get,set} = CM.Anchor.anchor "libs";
> set (SOME "lib");
```

(the step above where you set the anchor can probably be eliminated if we make an adjustment to `testsuite/test.cm`)

Then, build & run the test:

```
> CM.make "testsuite/test.cm";
```

Every time I make a code change, I just re-run the last command and see what happens; for me, the build usually completes in less than a second.

**Comment by ak3n** [comment]
@jonsterling omg! `rlwrap` is amazing. Thanks!

**Comment by jonsterling** [comment]
@ak3n I love `rlwrap` so much! hahaha...
