### ISSUE TITLE
enforce arities of CUST operators

### ISSUE THREAD

**Issue by jonsterling** [JonPRL/sml-red-jonprl#6]
As I was working on the elaboration semantics for signatures, I realized that we aren't actually enforcing that `CUST` operators carry the correct arities. We'll need to introduce a well-formedness check for all terms that are introduced into a signature, that walks the abt to find instances of `CUST[ϑ](a)`, looks up the arity `a'` assigned to `ϑ` in the signature, and checks that `a == a'`.

- [ ] update elaboration spec
- [x] update code

**Comment by jozefg** [comment]
I think I can do this :) I may need some feedback on how I did updating the spec but the code bit seems easy enough to write

**Comment by jonsterling** [comment]
Great, thanks! Let me know if you need any help with the spec.
