### ISSUE TITLE
Cool website / propaganda

### ISSUE THREAD

**Issue by jonsterling** [JonPRL/sml-red-jonprl#64]
We need a cool website, in the constructivist style. I made this site for [PrlConf](http://www.jonprl.org/prlconf.html), which I think has the basic aesthetic, but I have no idea what I'm doing.

If anyone wants to design and throw together a site for Red JonPRL, they get a free mug with a cool revolutionary slogan on it!

**Comment by markfarrell** [comment]
As mentioned at https://github.com/jonsterling/JonPRL/issues/247, I think it would be interesting to have a web-based front-end for the proof-assistant that:

* Feels like a notebook with theorems as input to cells and program extracts as output.
* Can bring up suggestions for tactics and lemmas to use to achieve a goal.

Thoughts?

**Comment by ak3n** [comment]
Looks like to be able to use SMLtoJs there is need to rewrite all `mlb` files (or patch smltojs), because it doesn't work now:

```
smltojs jonprl.mlb
* Error: while parsing basis file 'syntax.mlb' : I expect an 'end'(reached 'structure').
* Exiting!
```

e.g. it can't parse 

```
    local
      ../lib/cmlib/cmlib.mlb
    in
      structure StringOrdered
    end
```

All `mlb` in tests are like (https://github.com/melsman/mlkit/blob/master/js/test/rwp3.mlb):

```
$SML_LIB/basis/basis.mlb
$SML_LIB/basis/js.mlb
rwp.sig
rwp3.sml
rhtml.sig
rhtml.sml
color.sig
color.sml
rwidget.sig
rwidget.sml
```

**Comment by jonsterling** [comment]
Yeah, I came to the same conclusion; sadly looks like a non-starter, because we need the ability to impose abstraction by exporting only certain structures, etc.

**Comment by ak3n** [comment]
We can try to use mlton's llvm backend and emscripten or implement js backend for mlton. :)

**Comment by jonsterling** [comment]
Heh, that's an interesting project :smile:

**Comment by jonsterling** [comment]
In seriousness, I'm thinking the easier path forward may just be to develop a JonPRL server rather than running this stuff on the client... But it could become expensive.

**Comment by ak3n** [comment]
I have tried llvm backend and it has bugs. So, I think that it's easier to add a new js backend (and new bugs!) rather than fixing llvm's and using of emscripten.

I don't know if I can do it, but it's very interesting, yes.

**Comment by jonsterling** [comment]
@ak3n That would be very cool! I think that the MLKit have a paper on their JS backend. Not sure how relevant it is to MLton, but it might be worth a look.

Another option would be to try and get MLKit's implementation of the ML Basis System to support the full specification.

**Comment by MatthewFluet** [comment]
@ak3n What's the bug in MLton's llvm codegen? (Probably better to report as a [MLton/mlton](http://github.com/MLton/mlton) issue than in this thread.)

Extending MLKit's support for MLB is probably the best route, though I've played around a little with micro-language interpreters in a webpage via SMLtoJS and found it to be extremely slow.

**Comment by jonsterling** [comment]
I've made a new website here: http://www.jonprl.org/

Not much on it except it reflects the new branding.
